language: java
jdk:
  - oraclejdk8
env:
  - DITA_OT=3.3.2

install:
  - zip -r fox.jason.translate.xliff.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT/dita-ot-$DITA_OT.zip
  - unzip -q dita-ot-$DITA_OT.zip
  - chmod +x dita-ot-$DITA_OT/bin/dita
  - dita-ot-$DITA_OT/bin/dita --install https://github.com/jason-fox/fox.jason.unit-test/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita --install fox.jason.translate.xliff.zip

before_script:
  - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/fox.jason.translate.xliff -f xsl-instrument

script:
  - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/fox.jason.translate.xliff -f unit-test --output . -v

after_success:
  - cp dita-ot-$DITA_OT/plugins/fox.jason.unit-test/resource/pom.xml pom.xml
  - mvn clean org.eluder.coveralls:coveralls-maven-plugin:report   